#!/usr/bin/env node
// Regenerates cortex/INDEX.md — the progressive-disclosure map agents grep first.
// For every .md under cortex/ it records: path, title (first # heading), and a
// one-line description (first sentence of body, or YAML `description:` frontmatter).
// Dependency-free. Run after adding/renaming any cortex doc.
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const cortexRoot = join(here, '..');

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) { walk(full, out); continue; }
    if (name.endsWith('.md') && name !== 'INDEX.md') out.push(full);
  }
  return out;
}

function describe(text) {
  // frontmatter description: wins if present
  const fm = text.match(/^---\n[\s\S]*?\bdescription:\s*(.+)\n[\s\S]*?---/);
  if (fm) return fm[1].trim().replace(/^["']|["']$/g, '');
  const body = text.replace(/^---\n[\s\S]*?\n---\n/, '');
  const firstPara = body.split('\n').find(l => l.trim() && !l.startsWith('#') && !l.startsWith('*') && !l.startsWith('|'));
  if (!firstPara) return '';
  const sentence = firstPara.trim().split(/(?<=[.!?])\s/)[0];
  return sentence.length > 140 ? sentence.slice(0, 137) + '…' : sentence;
}

const files = walk(cortexRoot).sort();
const rows = files.map(f => {
  const text = readFileSync(f, 'utf8');
  const title = (text.match(/^#\s+(.+)$/m) || [, relative(cortexRoot, f)])[1];
  const tags = (text.match(/^tags:\s*(.+)$/m) || [, ''])[1].trim();
  return { path: relative(cortexRoot, f), title: title.trim(), desc: describe(text), tags };
});

let md = `# Cortex INDEX

*Auto-generated by \`tools/build-index.mjs\` — do not edit by hand. Grep this first,
then open only the files you need (progressive disclosure).*

| File | What it is | Tags |
|---|---|---|
`;
for (const r of rows) md += `| \`${r.path}\` | ${r.desc || r.title} | ${r.tags} |\n`;
md += `\n*${rows.length} documents indexed.*\n`;

writeFileSync(join(cortexRoot, 'INDEX.md'), md);
console.log(`✓ INDEX.md regenerated — ${rows.length} documents`);
