/**
 * AstroPrecise service worker.
 *
 * Install: a small, generated Home/Eclipse/offline shell.
 * Runtime: network-first navigations and release-critical code; on-demand
 * stale-while-revalidate for other same-origin assets.
 */

const V = "ap-v834";

/* PRECACHE_BEGIN — generated by tools/generate-sw-precache.mjs */
const PRECACHE = [
  './',
  './404.html',
  './accuracy.html',
  './angel-numbers.html',
  './aquarius.html',
  './aries.html',
  './assets/images/orbs/planets/jupiter.svg',
  './assets/images/orbs/planets/mars.svg',
  './assets/images/orbs/planets/mercury.svg',
  './assets/images/orbs/planets/moon.svg',
  './assets/images/orbs/planets/neptune.svg',
  './assets/images/orbs/planets/pluto.svg',
  './assets/images/orbs/planets/saturn.svg',
  './assets/images/orbs/planets/sun.svg',
  './assets/images/orbs/planets/uranus.svg',
  './assets/images/orbs/planets/venus.svg',
  './assets/images/seals/elements/air.svg',
  './assets/images/seals/elements/all.svg',
  './assets/images/seals/elements/earth.svg',
  './assets/images/seals/elements/fire.svg',
  './assets/images/seals/elements/water.svg',
  './assets/images/seals/instruments/chart.svg',
  './assets/images/seals/instruments/compatibility.svg',
  './assets/images/seals/instruments/horoscope.svg',
  './assets/images/seals/instruments/instrument.svg',
  './assets/images/seals/instruments/lifepath.svg',
  './assets/images/seals/instruments/oracle.svg',
  './assets/images/seals/instruments/shop.svg',
  './assets/images/seals/instruments/transits.svg',
  './assets/images/seals/planets/earth.svg',
  './assets/images/seals/planets/jupiter.svg',
  './assets/images/seals/planets/mars.svg',
  './assets/images/seals/planets/mercury.svg',
  './assets/images/seals/planets/moon.svg',
  './assets/images/seals/planets/neptune.svg',
  './assets/images/seals/planets/pluto.svg',
  './assets/images/seals/planets/saturn.svg',
  './assets/images/seals/planets/sun.svg',
  './assets/images/seals/planets/uranus.svg',
  './assets/images/seals/planets/venus.svg',
  './assets/images/seals/zodiac/aquarius.svg',
  './assets/images/seals/zodiac/aries.svg',
  './assets/images/seals/zodiac/cancer.svg',
  './assets/images/seals/zodiac/capricorn.svg',
  './assets/images/seals/zodiac/gemini.svg',
  './assets/images/seals/zodiac/leo.svg',
  './assets/images/seals/zodiac/libra.svg',
  './assets/images/seals/zodiac/pisces.svg',
  './assets/images/seals/zodiac/sagittarius.svg',
  './assets/images/seals/zodiac/scorpio.svg',
  './assets/images/seals/zodiac/taurus.svg',
  './assets/images/seals/zodiac/virgo.svg',
  './assets/images/zodiac-cards/aquarius.webp',
  './assets/images/zodiac-cards/aries.webp',
  './assets/images/zodiac-cards/cancer.webp',
  './assets/images/zodiac-cards/capricorn.webp',
  './assets/images/zodiac-cards/gemini.webp',
  './assets/images/zodiac-cards/leo.webp',
  './assets/images/zodiac-cards/libra.webp',
  './assets/images/zodiac-cards/pisces.webp',
  './assets/images/zodiac-cards/sagittarius.webp',
  './assets/images/zodiac-cards/scorpio.webp',
  './assets/images/zodiac-cards/taurus.webp',
  './assets/images/zodiac-cards/virgo.webp',
  './assets/textures/earth_clouds_sm.webp',
  './assets/textures/earth_lights_sm.webp',
  './assets/textures/earth_normal_sm.webp',
  './assets/textures/earth_sm.webp',
  './assets/textures/earth_specular_sm.webp',
  './assets/textures/jupiter_sm.webp',
  './assets/textures/mars_sm.webp',
  './assets/textures/mercury_sm.webp',
  './assets/textures/moon_sm.webp',
  './assets/textures/neptune_sm.webp',
  './assets/textures/saturn_ring_sm.webp',
  './assets/textures/saturn_sm.webp',
  './assets/textures/uranus_sm.webp',
  './assets/textures/venus_sm.webp',
  './cancer.html',
  './capricorn.html',
  './catalogue.html',
  './chart-view.html',
  './chart.html',
  './charts.html',
  './compatibility.html',
  './cosmic-story.html',
  './css/accuracy-page.css',
  './css/angel-numbers-page.css',
  './css/ap-affiliate-lite.css',
  './css/ap-ai-panel.css',
  './css/ap-atlas-chart.css',
  './css/ap-atlas-horoscope.css',
  './css/ap-atlas-shop.css',
  './css/ap-atlas-tokens.css',
  './css/ap-brand-nebula.css',
  './css/ap-cinematic-2026.css',
  './css/ap-cosmic-flight.css',
  './css/ap-eclipse-live-v834.css',
  './css/ap-engine-visuals.css',
  './css/ap-forms.css',
  './css/ap-frontier-pe.css',
  './css/ap-horizon-2026.css',
  './css/ap-launch-unified-v832.css',
  './css/ap-lite-chrome.css',
  './css/ap-living-sky-v834.css',
  './css/ap-logo-aurora.css',
  './css/ap-micro-2026.css',
  './css/ap-micro-delight.css',
  './css/ap-model-stage.css',
  './css/ap-model-window.css',
  './css/ap-motion.css',
  './css/ap-natal-sphere.css',
  './css/ap-observatory-enchanted.css',
  './css/ap-observatory-home.css',
  './css/ap-overhaul-s8.css',
  './css/ap-page-bridge.css',
  './css/ap-page-structure.css',
  './css/ap-palette-2026.css',
  './css/ap-planet-actions.css',
  './css/ap-reading.css',
  './css/ap-scroll-2026.css',
  './css/ap-shop-enchanted.css',
  './css/ap-site-polish.css',
  './css/ap-sky-news.css',
  './css/ap-structure-clean.css',
  './css/ap-visual-clarity.css',
  './css/celestial-seals.css',
  './css/chart-critical.css',
  './css/chart-hero-lcp-fonts.css',
  './css/chart-page-deferred.css',
  './css/chart.css',
  './css/charts-page.css',
  './css/compatibility-critical.css',
  './css/compatibility-page-deferred.css',
  './css/ephemeris-critical.css',
  './css/ephemeris-page.css',
  './css/ephemeris.css',
  './css/explore-page.css',
  './css/fonts.css',
  './css/horoscope-critical.css',
  './css/horoscope-page-deferred.css',
  './css/horoscope-personal.css',
  './css/index-home.css',
  './css/instrument-panel.css',
  './css/landing-gate.css',
  './css/lifepath-page.css',
  './css/links-page.css',
  './css/lite-critical.css',
  './css/main-lite.css',
  './css/main.css',
  './css/moment-page.css',
  './css/moonphase-page.css',
  './css/mysky-page.css',
  './css/name-numerology-page.css',
  './css/orrery-visual.css',
  './css/outreach-page.css',
  './css/profile-page.css',
  './css/quiz-page.css',
  './css/retrograde-page.css',
  './css/saturn-return-page.css',
  './css/shop-critical.css',
  './css/shop.css',
  './css/sign-page.css',
  './css/solar-return-page.css',
  './css/synastry-page.css',
  './css/tonight-page.css',
  './css/transits-page.css',
  './css/weekly-sky-page.css',
  './css/what-is-my-rising-sign-page.css',
  './css/why-page.css',
  './data/art-themes.json',
  './data/content-bank/core/aspects.json',
  './data/content-bank/core/deep-reading-sections.json',
  './data/content-bank/core/houses.json',
  './data/content-bank/core/planet-in-sign.json',
  './data/content-bank/core/rising-by-sign.json',
  './data/content-bank/daily/2026-08-09.json',
  './data/content-bank/daily/2026-08-10.json',
  './data/content-bank/daily/2026-08-11.json',
  './data/content-bank/daily/2026-08-12.json',
  './data/content-bank/daily/2026-08-13.json',
  './data/content-bank/daily/2026-08-14.json',
  './data/content-bank/daily/2026-08-15.json',
  './data/content-bank/daily/2026-08-16.json',
  './data/content-bank/daily/2026-08-17.json',
  './data/content-bank/daily/2026-08-18.json',
  './data/content-bank/daily/2026-08-19.json',
  './data/content-bank/daily/2026-08-20.json',
  './data/content-bank/daily/2026-08-21.json',
  './data/content-bank/daily/2026-08-22.json',
  './data/content-bank/daily/2026-08-23.json',
  './data/content-bank/daily/2026-08-24.json',
  './data/content-bank/manifest.json',
  './data/content-bank/monthly/2026-08.json',
  './data/content-bank/monthly/2026-09.json',
  './data/plate-demo-001.json',
  './data/sky_guides.json',
  './deep-reading.html',
  './eclipse.html',
  './ephemeris.html',
  './explore.html',
  './fonts/astro-glyphs.woff2',
  './fonts/cinzel-hero-700.woff2',
  './fonts/cinzel-normal-400.woff2',
  './fonts/cinzel-normal-600.woff2',
  './fonts/cinzel-normal-700.woff2',
  './fonts/cormorant-garamond-italic-400.woff2',
  './fonts/cormorant-garamond-italic-500.woff2',
  './fonts/cormorant-garamond-normal-400.woff2',
  './fonts/cormorant-garamond-normal-500.woff2',
  './fonts/cormorant-garamond-normal-600.woff2',
  './fonts/ibm-plex-mono-normal-400.woff2',
  './fonts/inter-normal-300.woff2',
  './fonts/inter-normal-400.woff2',
  './fonts/inter-normal-500.woff2',
  './fonts/inter-normal-600.woff2',
  './fonts/schibsted-grotesk-latin-var.woff2',
  './gemini.html',
  './guides.html',
  './horoscope.html',
  './img/design/eclipse-geometry-v1.svg',
  './img/design/eclipse-geometry.svg',
  './img/design/plate-enhanced.svg',
  './img/eclipse-geometry.svg',
  './img/favicon.svg',
  './img/logo-mark.svg',
  './img/logo.svg',
  './img/moment/earth-badge.webp',
  './img/moment/hero-framed.webp',
  './img/moment/how-it-works.webp',
  './img/obs-gallery-banner.webp',
  './img/plate-enhanced.svg',
  './img/zodiac-glyphs-row-b.jpg',
  './index-full.html',
  './index-lite.html',
  './index.html',
  './js/affiliate-social.js',
  './js/ambience.js',
  './js/angel-numbers.js',
  './js/ap-ai-assistant.js',
  './js/ap-asset-v.js',
  './js/ap-award-orrery.js',
  './js/ap-canvas-seals.js',
  './js/ap-chart-share.js',
  './js/ap-checkout-honest.js',
  './js/ap-cosmic-flight-tool.js',
  './js/ap-daily-bridge.js',
  './js/ap-daily-ritual.js',
  './js/ap-deep-link.js',
  './js/ap-eclipse-geometry-v834.js',
  './js/ap-eclipse-live-v834.js',
  './js/ap-eclipse-page.js',
  './js/ap-engine-visuals.js',
  './js/ap-error-beacon.js',
  './js/ap-feature-probes.js',
  './js/ap-footer-inject.js',
  './js/ap-gumroad-bridge.js',
  './js/ap-home-bootstrap.js',
  './js/ap-horizon-features.js',
  './js/ap-lite-detect.js',
  './js/ap-magnetic.js',
  './js/ap-moment-share.js',
  './js/ap-natal-sphere.js',
  './js/ap-nav-interplay.js',
  './js/ap-nav-model-v834.js',
  './js/ap-nav-model.js',
  './js/ap-nav-prefetch.js',
  './js/ap-observatory-entrance.js',
  './js/ap-observatory-v834.js',
  './js/ap-page-boot.js',
  './js/ap-page-bridge.js',
  './js/ap-personal-memory.js',
  './js/ap-planet-actions.js',
  './js/ap-post-purchase.js',
  './js/ap-reading-prefs.js',
  './js/ap-responsive-nav.js',
  './js/ap-safe-dom.js',
  './js/ap-scale-ladder.js',
  './js/ap-seedance.js',
  './js/ap-sign-defer-boot.js',
  './js/ap-sky-bridge.js',
  './js/ap-sky-news.js',
  './js/ap-sky-time.js',
  './js/ap-zodiac-constants.js',
  './js/app.js',
  './js/art-theme-library.js',
  './js/celestial-seals.js',
  './js/chart-page.js',
  './js/chart-render.js',
  './js/charts-dashboard.js',
  './js/compatibility-page.js',
  './js/content-service.js',
  './js/cosmic-story.js',
  './js/cosmos.js',
  './js/daily-transit.js',
  './js/daimon.js',
  './js/deep-reading.js',
  './js/defer-page-css.js',
  './js/echoes.js',
  './js/eclipse-reading.js',
  './js/ecliptic-dial-data.js',
  './js/effects.js',
  './js/element-seals.js',
  './js/ephemeris.js',
  './js/explore-boot.js',
  './js/fieldweather.js',
  './js/footer-chrome.js',
  './js/gumroad-unlock.js',
  './js/hero-instrument.js',
  './js/home-daily.js',
  './js/home-match.js',
  './js/home-sign-picker.js',
  './js/horoscope-engine.js',
  './js/horoscope-page.js',
  './js/horoscope-subscribe.js',
  './js/horoscope-wheel-poster.js',
  './js/icons.js',
  './js/instrument.js',
  './js/journey.js',
  './js/lazy-zodiac-cards.js',
  './js/lightcone.js',
  './js/lite-orrery.js',
  './js/lite-shell-boot.js',
  './js/lite-sky-dock.js',
  './js/moment-page.js',
  './js/moonphase.js',
  './js/name-numerology.js',
  './js/oracle.js',
  './js/orrery-loader.js',
  './js/orrery.js',
  './js/personalization-engine.js',
  './js/plate-fingerprint.js',
  './js/profile.js',
  './js/quiz.js',
  './js/raf-core.js',
  './js/reading-format.js',
  './js/reading-templates.json',
  './js/retrograde.js',
  './js/saturn-return.js',
  './js/scale-journey-chapters.js',
  './js/scale-journey.js',
  './js/seo-tools.js',
  './js/shop-art-themes.js',
  './js/shop-commerce.js',
  './js/shop-curated.js',
  './js/shop-page-boot.js',
  './js/shop-wallpaper-lead.js',
  './js/sign-daily.js',
  './js/sign-page-boot.js',
  './js/sky-guides.js',
  './js/starcatalog.js',
  './js/synastry-shared.js',
  './js/tonight.js',
  './js/tool-cards.js',
  './js/vendor/gsap.min.js',
  './js/vendor/three-r128-CopyShader.js',
  './js/vendor/three-r128-EffectComposer.js',
  './js/vendor/three-r128-GammaCorrectionShader.js',
  './js/vendor/three-r128-LuminosityHighPassShader.js',
  './js/vendor/three-r128-RenderPass.js',
  './js/vendor/three-r128-ShaderPass.js',
  './js/vendor/three-r128-UnrealBloomPass.js',
  './js/vendor/three/jsm/postprocessing/EffectComposer.js',
  './js/vendor/three/jsm/postprocessing/MaskPass.js',
  './js/vendor/three/jsm/postprocessing/OutputPass.js',
  './js/vendor/three/jsm/postprocessing/Pass.js',
  './js/vendor/three/jsm/postprocessing/RenderPass.js',
  './js/vendor/three/jsm/postprocessing/ShaderPass.js',
  './js/vendor/three/jsm/postprocessing/UnrealBloomPass.js',
  './js/vendor/three/jsm/shaders/CopyShader.js',
  './js/vendor/three/jsm/shaders/LuminosityHighPassShader.js',
  './js/vendor/three/jsm/shaders/OutputShader.js',
  './js/void-orrery-adapter.js',
  './js/weekly-sky.js',
  './js/zodiac-sphere.js',
  './leo.html',
  './libra.html',
  './lifepath.html',
  './links.html',
  './llms.txt',
  './manifest.json',
  './moment.html',
  './moonphase.html',
  './mysky.html',
  './name-numerology.html',
  './offline.html',
  './pisces.html',
  './privacy.html',
  './profile.html',
  './quiz.html',
  './retrograde.html',
  './robots.txt',
  './sagittarius.html',
  './sample-reading.html',
  './saturn-return.html',
  './scorpio.html',
  './shop.html',
  './sitemap.xml',
  './solar-return.html',
  './synastry.html',
  './taurus.html',
  './terms.html',
  './this-weeks-sky.html',
  './tonight.html',
  './transits.html',
  './virgo.html',
  './what-is-my-rising-sign.html',
  './why.html',
];
/* PRECACHE_END */

/* Keep runtime definitions below PRECACHE_END. Commit be871d1 once put them
   inside the generated block; regeneration deleted them and broke every worker
   lifecycle event. The generator now fails closed if they move. */

function canonicalAssetKey(value) {
  const u = new URL(typeof value === 'string' ? value : value.url, self.registration.scope);
  u.search = '';
  u.hash = '';
  return u.href;
}

// Until the next generator run, accept the historical broad PRECACHE block but
// install only its small launch subset. Generated blocks declare launch-shell
// mode and contain no optional long tail, so every listed entry is atomic CORE.
const LEGACY_CORE = /(?:^\.\/)?(?:index\.html|eclipse\.html|offline\.html|manifest\.webmanifest|js\/(?:app|ap-page-boot|ap-nav-model(?:-v\d+)?|ap-asset-v|ap-footer-inject|void-orrery-adapter|ap-observatory(?:-controls)?(?:-v\d+)?|ap-sky-time|ap-eclipse-(?:live|contact)(?:-v\d+)?|ephemeris|eclipse-reading)\.js|js\/reading-templates\.json|css\/(?:main-lite|ap-overhaul-s8|ap-palette-2026|ap-living-sky-v\d+|ap-home-v\d+|ap-eclipse(?:-live)?-v\d+)\.css|fonts\/(?:schibsted-grotesk-latin-var|cormorant-garamond-normal-600)\.woff2|img\/(?:logo-mark|eclipse-geometry)\.svg|img\/editorial\/eclipse-launch-2026-v\d+\.webp)$/;
const CORE = (typeof PRECACHE_MODE !== 'undefined' && PRECACHE_MODE === 'launch-shell')
  ? PRECACHE
  : PRECACHE.filter(u => u === './' || LEGACY_CORE.test(u));
const CORE_KEYS = new Set(CORE.map(canonicalAssetKey));
const OWN_CACHE_NAME = /^ap-v\d+$/;

function cacheableResponse(request, response) {
  if (!response || response.status !== 200 || response.type !== 'basic') return false;
  if (request.cache === 'no-store') return false;
  if (/\bno-store\b/i.test(response.headers.get('cache-control') || '')) return false;
  if ((response.headers.get('vary') || '').trim() === '*') return false;
  return true;
}

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(V).then(c => {
      // A worker never claims clients with half a shell. cache:'reload' also
      // prevents the browser HTTP cache baking the previous release into V.
      const installCore = CORE.map(u => new Request(canonicalAssetKey(u), { cache: 'reload' }));
      return c.addAll(installCore);
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    (async () => {
      const keys = await caches.keys();
      // Delete only AstroPrecise release caches. Other applications sharing an
      // origin must never lose their Cache Storage because this worker updated.
      await Promise.all(keys.filter(k => k !== V && OWN_CACHE_NAME.test(k)).map(k => caches.delete(k)));

      const cache = await caches.open(V);
      // Older workers used query-bearing cache keys. Besides wasting space,
      // chart URLs could expose birth details in DevTools. Current keys are
      // canonical and query-free; purge any survivor before claiming clients.
      const requests = await cache.keys();
      await Promise.all(requests.filter(request => {
        try { return Boolean(new URL(request.url).search); } catch (_) { return false; }
      }).map(request => cache.delete(request)));

      if (self.registration.navigationPreload) {
        try { await self.registration.navigationPreload.enable(); } catch (_) {}
      }
      await self.clients.claim();
    })()
  );
});

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  if (url.origin !== self.location.origin) return;
  if (/\/api(?:\/|$)/i.test(url.pathname)) return;

  // Media (video/audio) — never intercept. Byte-range streaming must hit the
  // network directly; SW caching/serving full responses stalls <video> playback.
  if (/\.(mp4|webm|m4v|mov|ogv|m4a|mp3|ogg|wav)$/i.test(url.pathname) ||
      e.request.headers.has('range')) return;

  const isNav = e.request.mode === 'navigate';
  const path = url.pathname.replace(/\/+$/, '') || '/';
  const cacheKey = canonicalAssetKey(e.request);
  // Generated shell entries and route engines revalidate through the HTTP cache.
  // The release-specific cache lookup below prevents old-cache bleed entirely.
  const isCritical = CORE_KEYS.has(cacheKey) ||
    /\/js\/(?:app|chart-page|horoscope-page|cosmos|orrery|orrery-loader|orrery-webgl|void-orrery-adapter|ambience|eclipse-reading|deep-reading|plate-fingerprint|ap-sky-news|ap-natal-sphere|ap-checkout-honest|ap-gumroad-bridge|gumroad-unlock|ap-award-orrery|ap-home-bootstrap|hero-instrument|effects|ephemeris|lite-orrery|lite-shell-boot|ap-footer-inject|ap-page-boot|ap-asset-v)\.js$/.test(path) ||
    /\/js\/(?:explore-boot|ap-nav-model|ap-observatory|ap-observatory-controls|ap-eclipse-geometry|ap-eclipse-live|ap-eclipse-contact)(?:-v\d+)?\.js$/.test(path) ||
    /\/css\/(?:main|main-lite|ap-model-window|ap-observatory-home|ap-brand-nebula|ap-sky-news|ap-natal-sphere|ap-palette-2026)\.css$/.test(path) ||
    /\/css\/(?:explore-page|ap-living-sky|ap-home|ap-shop|ap-eclipse|ap-chart|ap-daily)(?:-v\d+)?\.css$/.test(path);

  const activeCache = caches.open(V);
  const mayReadCache = e.request.cache !== 'no-store';
  const cachedResponse = mayReadCache
    ? activeCache.then(cache => cache.match(cacheKey))
    : Promise.resolve(undefined);

  const requestNetwork = () => (isNav || isCritical || /^(?:no-cache|reload)$/.test(e.request.cache))
    ? fetch(e.request.url, { cache: 'no-cache', credentials: 'same-origin' })
    : fetch(e.request);

  // Navigation preload starts the document request while the worker wakes. If
  // unsupported or empty, fall back to the normal network request.
  const rawNetwork = isNav && e.preloadResponse
    ? e.preloadResponse.then(response => response || requestNetwork(), () => requestNetwork())
    : requestNetwork();

  // Hold runtime writes alive. The previous fire-and-forget cache.put could be
  // terminated as soon as respondWith settled, making "available offline" random.
  const cacheUpdate = rawNetwork.then(response => {
    if (!cacheableResponse(e.request, response)) return undefined;
    const copy = response.clone();
    return activeCache.then(cache => cache.put(cacheKey, copy));
  }).catch(() => undefined);
  e.waitUntil(cacheUpdate);

  const networkResponse = rawNetwork.catch(() => null);
  e.respondWith((async () => {
    const cache = await activeCache;
    const cached = await cachedResponse;

    if (isNav) {
      const network = await networkResponse;
      // Preserve real online 404/500 responses. The old `res.ok` gate disguised
      // them as the offline page and made broken links look like lost internet.
      if (network) return network;
      if (cached) return cached;
      const offline = await cache.match(canonicalAssetKey('./offline.html'));
      if (offline) return offline;
      const home = await cache.match(canonicalAssetKey('./'));
      if (home) return home;
      return new Response('AstroPrecise is offline. Reconnect and try again.', {
        status: 503,
        headers: { 'Content-Type': 'text/plain; charset=utf-8' },
      });
    }

    if (isCritical || /^(?:no-cache|reload)$/.test(e.request.cache)) {
      const network = await networkResponse;
      // A received HTTP response is authoritative, including 404/500. Only a
      // rejected/no-response network attempt may fall back to the frozen cache.
      if (network) return network;
      return cached || Response.error();
    }

    // On-demand stale-while-revalidate. No bulk warm-up competes with WebGL.
    return cached || await networkResponse || Response.error();
  })());
});





