/**
 * AstroPrecise service worker.
 *
 * Install: a small, generated Home/Eclipse/offline shell.
 * Runtime: network-first navigations and release-critical code; on-demand
 * stale-while-revalidate for other same-origin assets.
 */

const V = "ap-v882";

/* PRECACHE_BEGIN — generated by tools/generate-sw-precache.mjs */
const PRECACHE_MODE = 'launch-shell';
const PRECACHE = [
  './',
  './assets/textures/earth_clouds_sm.webp',
  './assets/textures/earth_lights_sm.webp',
  './assets/textures/earth_normal_sm.webp',
  './assets/textures/earth_sm.webp',
  './assets/textures/earth_specular_sm.webp',
  './assets/textures/jupiter_sm.webp',
  './assets/textures/mars_sm.webp',
  './assets/textures/mercury_sm.webp',
  './assets/textures/moon_sm.webp',
  './assets/textures/neptune_sm.webp',
  './assets/textures/saturn_ring_sm.webp',
  './assets/textures/saturn_sm.webp',
  './assets/textures/uranus_sm.webp',
  './assets/textures/venus_sm.webp',
  './css/ap-eclipse-live-v834.css',
  './css/ap-eclipse-v835.css',
  './css/ap-footer-v835.css',
  './css/ap-home-v835.css',
  './css/ap-keep-sky.css',
  './css/ap-living-sky-v834.css',
  './css/ap-mystic-cards-v835.css',
  './css/ap-phone-pass.css',
  './css/fonts.css',
  './eclipse.html',
  './favicon.ico',
  './favicon.svg',
  './fonts/astro-glyphs.woff2',
  './fonts/cinzel-normal-400.woff2',
  './fonts/cinzel-normal-600.woff2',
  './fonts/cinzel-normal-700.woff2',
  './fonts/cormorant-garamond-italic-400.woff2',
  './fonts/cormorant-garamond-italic-500.woff2',
  './fonts/cormorant-garamond-normal-400.woff2',
  './fonts/cormorant-garamond-normal-500.woff2',
  './fonts/cormorant-garamond-normal-600.woff2',
  './fonts/ibm-plex-mono-normal-400.woff2',
  './fonts/inter-normal-300.woff2',
  './fonts/inter-normal-400.woff2',
  './fonts/inter-normal-500.woff2',
  './fonts/inter-normal-600.woff2',
  './fonts/schibsted-grotesk-latin-var.woff2',
  './img/eclipse-geometry.svg',
  './img/logo-mark.svg',
  './img/orrery/env_nebula_cool_sm.webp',
  './index.html',
  './js/ap-eclipse-contact-v835.js',
  './js/ap-eclipse-edition-v841.js',
  './js/ap-eclipse-geometry-v834.js',
  './js/ap-eclipse-live-v834.js',
  './js/ap-footer-inject.js',
  './js/ap-mystic-cards-v835.js',
  './js/ap-nav-model.js',
  './js/ap-nav-prefetch.js',
  './js/ap-observatory-controls-v835.js',
  './js/ap-observatory-v834.js',
  './js/ap-sky-time.js',
  './js/eclipse-reading.js',
  './js/ephemeris.js',
  './js/gumroad-unlock.js',
  './js/orbitlab-bodies.js',
  './js/orbitlab-orbital-math.js',
  './js/orrery-webgl.js',
  './js/reading-templates.json',
  './js/vendor/three/jsm/postprocessing/EffectComposer.js',
  './js/vendor/three/jsm/postprocessing/MaskPass.js',
  './js/vendor/three/jsm/postprocessing/OutputPass.js',
  './js/vendor/three/jsm/postprocessing/Pass.js',
  './js/vendor/three/jsm/postprocessing/RenderPass.js',
  './js/vendor/three/jsm/postprocessing/ShaderPass.js',
  './js/vendor/three/jsm/postprocessing/UnrealBloomPass.js',
  './js/vendor/three/jsm/shaders/CopyShader.js',
  './js/vendor/three/jsm/shaders/LuminosityHighPassShader.js',
  './js/vendor/three/jsm/shaders/OutputShader.js',
  './js/vendor/three/three.module.min.js',
  './js/void-orrery-adapter.js',
  './manifest.json',
  './offline.html',
];
/* PRECACHE_END */

/* Keep runtime definitions below PRECACHE_END. Commit be871d1 once put them
   inside the generated block; regeneration deleted them and broke every worker
   lifecycle event. The generator now fails closed if they move. */

function canonicalAssetKey(value) {
  const u = new URL(typeof value === 'string' ? value : value.url, self.registration.scope);
  u.search = '';
  u.hash = '';
  return u.href;
}

// Until the next generator run, accept the historical broad PRECACHE block but
// install only its small launch subset. Generated blocks declare launch-shell
// mode and contain no optional long tail, so every listed entry is atomic CORE.
const LEGACY_CORE = /(?:^\.\/)?(?:index\.html|eclipse\.html|offline\.html|manifest\.webmanifest|js\/(?:app|ap-page-boot|ap-nav-model(?:-v\d+)?|ap-asset-v|ap-footer-inject|void-orrery-adapter|ap-observatory(?:-controls)?(?:-v\d+)?|ap-sky-time|ap-eclipse-(?:live|contact)(?:-v\d+)?|ephemeris|eclipse-reading)\.js|js\/reading-templates\.json|css\/(?:main-lite|ap-overhaul-s8|ap-palette-2026|ap-living-sky-v\d+|ap-home-v\d+|ap-eclipse(?:-live)?-v\d+)\.css|fonts\/(?:schibsted-grotesk-latin-var|cormorant-garamond-normal-600)\.woff2|img\/(?:logo-mark|eclipse-geometry)\.svg|img\/editorial\/eclipse-launch-2026-v\d+\.webp)$/;
const CORE = (typeof PRECACHE_MODE !== 'undefined' && PRECACHE_MODE === 'launch-shell')
  ? PRECACHE
  : PRECACHE.filter(u => u === './' || LEGACY_CORE.test(u));
const CORE_KEYS = new Set(CORE.map(canonicalAssetKey));
const OWN_CACHE_NAME = /^ap-v\d+$/;

function cacheableResponse(request, response) {
  if (!response || response.status !== 200 || response.type !== 'basic') return false;
  if (request.cache === 'no-store') return false;
  if (/\bno-store\b/i.test(response.headers.get('cache-control') || '')) return false;
  if ((response.headers.get('vary') || '').trim() === '*') return false;
  return true;
}

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(V).then(c => {
      // A worker never claims clients with half a shell. cache:'reload' also
      // prevents the browser HTTP cache baking the previous release into V.
      const installCore = CORE.map(u => new Request(canonicalAssetKey(u), { cache: 'reload' }));
      return c.addAll(installCore);
    }).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', e => {
  e.waitUntil(
    (async () => {
      const keys = await caches.keys();
      // Delete only AstroPrecise release caches. Other applications sharing an
      // origin must never lose their Cache Storage because this worker updated.
      await Promise.all(keys.filter(k => k !== V && OWN_CACHE_NAME.test(k)).map(k => caches.delete(k)));

      const cache = await caches.open(V);
      // Older workers used query-bearing cache keys. Besides wasting space,
      // chart URLs could expose birth details in DevTools. Current keys are
      // canonical and query-free; purge any survivor before claiming clients.
      const requests = await cache.keys();
      await Promise.all(requests.filter(request => {
        try { return Boolean(new URL(request.url).search); } catch (_) { return false; }
      }).map(request => cache.delete(request)));

      if (self.registration.navigationPreload) {
        try { await self.registration.navigationPreload.enable(); } catch (_) {}
      }
      await self.clients.claim();
    })()
  );
});

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  if (url.origin !== self.location.origin) return;
  if (/\/api(?:\/|$)/i.test(url.pathname)) return;

  // Media (video/audio) — never intercept. Byte-range streaming must hit the
  // network directly; SW caching/serving full responses stalls <video> playback.
  if (/\.(mp4|webm|m4v|mov|ogv|m4a|mp3|ogg|wav)$/i.test(url.pathname) ||
      e.request.headers.has('range')) return;

  const isNav = e.request.mode === 'navigate';
  const path = url.pathname.replace(/\/+$/, '') || '/';
  const cacheKey = canonicalAssetKey(e.request);
  // Generated shell entries and route engines revalidate through the HTTP cache.
  // The release-specific cache lookup below prevents old-cache bleed entirely.
  const isCritical = CORE_KEYS.has(cacheKey) ||
    /\/js\/(?:app|chart-page|horoscope-page|cosmos|orrery|orrery-loader|orrery-webgl|void-orrery-adapter|ambience|eclipse-reading|deep-reading|ap-natal-reading|plate-fingerprint|ap-gumroad-bridge|gumroad-unlock|hero-instrument|effects|ephemeris|lite-orrery|ap-footer-inject|ap-page-boot|ap-asset-v)\.js$/.test(path) ||
    /\/js\/(?:ap-nav-model|ap-observatory|ap-observatory-controls|ap-eclipse-geometry|ap-eclipse-live|ap-eclipse-contact)(?:-v\d+)?\.js$/.test(path) ||
    /\/css\/(?:main|main-lite|ap-model-window|ap-brand-nebula|ap-palette-2026)\.css$/.test(path) ||
    /\/css\/(?:ap-living-sky|ap-home|ap-shop|ap-eclipse|ap-chart|ap-daily)(?:-v\d+)?\.css$/.test(path);

  const activeCache = caches.open(V);
  const mayReadCache = e.request.cache !== 'no-store';
  const cachedResponse = mayReadCache
    ? activeCache.then(cache => cache.match(cacheKey))
    : Promise.resolve(undefined);

  const requestNetwork = () => (isNav || isCritical || /^(?:no-cache|reload)$/.test(e.request.cache))
    ? fetch(e.request.url, { cache: 'no-cache', credentials: 'same-origin' })
    : fetch(e.request);

  // Navigation preload starts the document request while the worker wakes. If
  // unsupported or empty, fall back to the normal network request.
  const rawNetwork = isNav && e.preloadResponse
    ? e.preloadResponse.then(response => response || requestNetwork(), () => requestNetwork())
    : requestNetwork();

  // Hold runtime writes alive. The previous fire-and-forget cache.put could be
  // terminated as soon as respondWith settled, making "available offline" random.
  const cacheUpdate = rawNetwork.then(response => {
    if (!cacheableResponse(e.request, response)) return undefined;
    const copy = response.clone();
    return activeCache.then(cache => cache.put(cacheKey, copy));
  }).catch(() => undefined);
  e.waitUntil(cacheUpdate);

  const networkResponse = rawNetwork.catch(() => null);
  e.respondWith((async () => {
    const cache = await activeCache;
    const cached = await cachedResponse;

    if (isNav) {
      const network = await networkResponse;
      // Preserve real online 404/500 responses. The old `res.ok` gate disguised
      // them as the offline page and made broken links look like lost internet.
      if (network) return network;
      if (cached) return cached;
      const offline = await cache.match(canonicalAssetKey('./offline.html'));
      if (offline) return offline;
      const home = await cache.match(canonicalAssetKey('./'));
      if (home) return home;
      return new Response('AstroPrecise is offline. Reconnect and try again.', {
        status: 503,
        headers: { 'Content-Type': 'text/plain; charset=utf-8' },
      });
    }

    if (isCritical || /^(?:no-cache|reload)$/.test(e.request.cache)) {
      const network = await networkResponse;
      // A received HTTP response is authoritative, including 404/500. Only a
      // rejected/no-response network attempt may fall back to the frozen cache.
      if (network) return network;
      return cached || Response.error();
    }

    // On-demand stale-while-revalidate. No bulk warm-up competes with WebGL.
    return cached || await networkResponse || Response.error();
  })());
});





